### PR TITLE
All employees page

### PR DESCRIPTION
**Pull request by Theedon**

### CODE REVIEW

**Comment by Sosaristic** [comment]
bro nice job, but i believe that u can do better. First the designs, the action icons are too large and then secondly when u clicked on a single employee it should be dynamic routing not displaying the employee in an overlay

**Comment by Sosaristic** [comment]
bro nice job, but i believe that u can do better. First the designs, the action icons are too large and then secondly when u clicked on a single employee it should be dynamic routing not displaying the employee in an overlay. lastly is the mobile view, its not responsive, everything is clustered on mobile view

**Review by Sosaristic — CHANGES_REQUESTED** [review]
bro nice job, but i believe that u can do better. First the designs, the action icons are too large and then secondly when u clicked on a single employee it should be dynamic routing not displaying the employee in an overlay. lastly is the mobile view, its not responsive, everything is clustered on mobile view

**Comment by Theedon** [comment]
> bro nice job, but i believe that u can do better. First the designs, the action icons are too large and then secondly when u clicked on a single employee it should be dynamic routing not displaying the employee in an overlay

Noted, but do we have a figma design for how the single employee page should look like. If so, please make a comment on it on the figma file

**Pull request closed without merging**
